--[[
	This file was generated by Lokasenna_Repeat Action - Add new action.lua
--]]

	
	act = "_RS574b2b34fc7b012a307d7b9f637fe187111f3726"
	interval = 2
	midi = false
	
	script_path = debug.getinfo(1,'S').source:match[[^@?(.*[\/])[^\/]-$]]
	dofile(script_path .. "Liu_Repeat action_for checing MIDI device.lua")
	
